### PR TITLE
Install to standard locations

### PR DESCRIPTION
**Pull request by candrews**
Install to standard locations in /usr/{lib,include}/lib (as opposed to /usr/hsa/{lib,include}/hsa)

/usr/hsa isn't an FHS standard location so it can't be used by Linux distros such as Gentoo, Fedora, Red Hat, etc

### CODE REVIEW

**Comment by jlgreathouse** [comment]
Hi @candrews 

Thanks for the PR. I'm not sure we will be able to immediately. We are currently working through the process of getting all of our teams aligned on a standard installation process (and set of locations) as per  [this request](https://github.com/RadeonOpenCompute/ROCm/issues/647). Until we can make sure that there are no other ROCm packages trying to hard-code `/opt/rocm/hsa/lib/hsa` and `/opt/rocm/hsa/include/hsa`, etc. we can't really merge in this patch. Since ROCr sits at the base a great deal of our stack, we need to put changes through some rigorous testing, and we must move in sync with a lot of other projects.

That said, your patch is appreciated, and we will hopefully keep you up to date as this process moves forward.

**Comment by candrews** [comment]
Thanks for that, I look forward to updates. I'm eager to get this into Gentoo.... hopefully I can get it there.

FYI, here's a related PR: https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/pull/25

**Comment by candrews** [comment]
It looks like at least RadeonOpenCompute/ROCT-Thunk-Interface now installs to the standard locations and it uses GNUInstallDirs as this PR does.

Perhaps this PR can be merged now?

**Comment by candrews** [comment]
I've rebased this PR.

@jlgreathouse (or anyone else appropriate) can you please consider merging these changes?

**Comment by candrews** [comment]
@jlgreathouse @skeelyamd @chsigg can you please take a look at this?

I'd really like to get this PR merged. Thank you!

**Comment by chsigg** [comment]
Hi Craig, I'm not associated with AMD or a reviewer of ROCm changes. You might have picked up my name from ROCm PRs to TensorFlow.

**Pull request closed without merging**
