### PR TITLE
Use CMAKE_INSTALL_*

### PR DESCRIPTION
**Pull request by Mystro256**
I created this just to help the Fedora package to get updated.

I believe is planned for one of the 5.x releases, but I would like to create this pull request for public tracking purposes.

Also anyone can easily cherry-pick/format-patch this in the meantime.

### CODE REVIEW

**Comment by awehrfritz** [comment]
Any progress on getting this merged? The changes look all good to me and quite straight forward.

**Comment by Mystro256** [comment]
@awehrfritz I needed to rework the patch, and got it merged internally. It should be pushed with the 5.2 release I think

**Comment by awehrfritz** [comment]
Thanks for the heads-up @Mystro256. Given that you are in a quite unique position where you submit patches as a "member of the open source community", but have access to the internal development teams, do you think it's worth at all to go through the trouble of submitting this kind of PRs at all?

I'm asking since building the ROCm stack from source is a major pain in the neck, with some components requiring even shell scripts that set up and move things around the actual build system ([hipamd](https://github.com/ROCm-Developer-Tools/hipamd) is an example for that), and still don't compile correctly without major surgery. This should never be the case and almost always points to a poorly designed build system in the first place.

In fact, I'm really wondering how the deb/rpm packages are built since I have not been able so far to reproduce them somehow (even under on supported Ubuntu or RHEL-clone systems with all required dependencies installed).

**Comment by Mystro256** [comment]
Closing as this issue is fixed in 5.2.0

@awehrfritz I thought I already responded to this thread but apparently not.
Most ROCm packages use cpack, e.g.:

cmake .
make
make package

There's documentation online on how to use cpack:
https://cmake.org/cmake/help/latest/module/CPack.html

I pushed this patch here because then users can take advantage of them before they're pushed to github.
ROCR is a bit tricky because the mirroring does not preserve git history, and the dev branch is not regularly synced, unlike other rocm projects

Regarding hipamd, I'm aware of the issues and have been talking with the developers about it. Right now I have a fedora package that's a WIP if that helps you at all:
https://copr.fedorainfracloud.org/coprs/mystro256/rocm-hip/
I'm unaware of any ETA on the HIP issues, but the issues are being reported as distros are attempting to package it.

**Comment by awehrfritz** [comment]
Great! Thanks @Mystro256. I will have a look at the 5.2 release, as well as your Fedora packages. Those seem to be the best option at the moment.

**Pull request closed without merging**
